### ISSUE TITLE
Interpolation Graph

### ISSUE THREAD

**Issue by samueltenka** [pmauldin/TweetSense#1]
![interpolationgraph_0316am](https://cloud.githubusercontent.com/assets/5819389/5788237/bc8111bc-9df7-11e4-9281-0f8eb3b8b981.png)

**Comment by samueltenka** [comment]
Illustrates numeric output of TwitterAnalysis/Interpolator.py

**Comment by pmauldin** [comment]
Niiiiceeee #sexy
